print("O meu nome é" , "Eliel Mendes Oliveira")
print("O meu RA é" , 1901498)
print("O meu curso é \n" , "ADS")
print("minha idade é" , "33 anos")
print("meu peso é" , "70 kg")
print("meu gênero é" , "masculino")
print(" a média aritmética é \n" , ((8.0 + 7.5 + 4.5 + 9)/ 4) )
print("o calculo do quadrado é" , 350*350)
print("o calculo da área de um raio com 5cm é de" , 3.14*5**2 , "cm")
