print("Notas do Aluno")
Nome = input("Digite seu Nome")
a1 = int(input("Digite sua primeira nota"))
a2 = int(input("Digite sua segunda nota"))
a3 = int(input("Digite sua terceira nota"))
print(Nome , "Sua média aritmetica de notas é" , ((a1+a2+a3)/3))
